# Generated by Django 5.0.1 on 2024-03-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='Fillier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
